# docker-compose.yml

version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: worksong
      POSTGRES_PASSWORD: worksong
      POSTGRES_DB: worksongdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  worksong-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worksong-app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: worksong
      DATABASE_PASSWORD: worksong
      DATABASE_NAME: worksongdb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["sh", "-c", "/usr/local/bin/wait-for postgres:5432 -- npx prisma migrate deploy && yarn start:prod"]

volumes:
  postgres-data: